spring:
  datasource:
    url: "jdbc:postgresql://dpg-cve2ci3tq21c73eautlg-a:5432/hex_db_u1kb?password=Y9Q6OOpxmQwIxwmqVed3lCLSAimHYV4k&user=hex_db_q1sg_user"
    username: hex_db_q1sg_user
    password: Y9Q6OOpxmQwIxwmqVed3lCLSAimHYV4k

