spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "JDBC_DATABASE_URL, jdbc:h2:mem:project");
    username:
    password:
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
