logging:
  level:
    root: warn
    #org.springframework.security: trace

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    default: dev
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    enabled: true
    path: /doc_ui.html
  api-docs:
    path: /api-docs
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem