name: myWorkFlow

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
    
      uses: actions/setup-java@v4
      with:
            distribution: temurin
            java-version: 21-ea

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Init gradle wrapper
      run: gradle wrapper

    - name: build
      run: gradle build

    - name: test
      run: gradle test

    - name: jacocoTestReport
      run: 	./gradlew jacocoTestReport 

    - name: Submit
      uses: qltysh/qlty-action/coverage@main
      with:
        coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: build/reports/jacoco/test/jacocoTestReport.xml
      
