name: myWorkFlow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
    
      uses: actions/setup-java@v4
      with:
            distribution: temurin
            java-version: 21-ea

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Init gradle wrapper
      run: gradle wrapper

    - name: build
      run: gradle build

    - name: test
      run: gradle test

    - name: jacocoTestReport
      run: make report
      
    - name: Download Code Climate Test Reporter
      run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
  
    - name: Format coverage for Code Climate
      run: |
          ./cc-test-reporter format-coverage build/reports/jacoco/test/jacocoTestReport.xml
      env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST}}
          
    - name: Upload coverage to Code Climate
      run: |
          ./cc-test-reporter upload-coverage
      env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST}}
