name: myWorkFlow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
    
      uses: actions/setup-java@v4
      with:
            distribution: temurin
            java-version: 21-ea

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
    - name: Init gradle wrapper
      run: gradle wrapper

    - name: build
      run: gradle build

    - name: test
      run: make test
  
    - name: Test Coverage  
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        workingDirectory: ${{github.workspace}}/app
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST}}
        JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
      with:
        coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
        coverageCommand: make report
